# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6526b5ab1cda1a97692b6c2e8dbfe60ac99187167abec3229b0eb5e2f452db264a952dea618d3ae24335eaf44056ff3af88c818e1062e3dec21fc6a0c17bb5b5

test:
  secret_key_base: 535037eaa367bfecf1cff12c6ca721c48adcfc6fb12b40213af87987c5122b3342d09f0d9a11436dffebb4a7af63d16e4f607813dea98fa7ff459aa9ce1a0457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
